stages:
  - test
  - build

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

cache:
  paths:
    - .m2/repository/

test-compile:
  stage: test
  tags:
    - self-hosted
  script:
    - mvn compile -q

build-war:
  stage: build
  tags:
    - self-hosted
  script:
    - mvn clean package -DskipTests
  artifacts:
    paths:
      - target/coffee-shop.war
    expire_in: 1 hour
